/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CipherScribeReview {
  export type PaperStatsStruct = {
    paperId: BytesLike;
    title: string;
    track: string;
    authorHash: string;
    reviewCount: BigNumberish;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
  };

  export type PaperStatsStructOutput = [
    paperId: string,
    title: string,
    track: string,
    authorHash: string,
    reviewCount: bigint,
    createdAt: bigint,
    updatedAt: bigint
  ] & {
    paperId: string;
    title: string;
    track: string;
    authorHash: string;
    reviewCount: bigint;
    createdAt: bigint;
    updatedAt: bigint;
  };
}

export interface CipherScribeReviewInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_SCORE"
      | "MIN_SCORE"
      | "getPaper"
      | "getPaperIds"
      | "getPlainSum"
      | "listPapers"
      | "owner"
      | "prepareFinalScore"
      | "protocolId"
      | "registerPaper"
      | "renounceOwnership"
      | "reviewerHasSubmitted"
      | "shareEncryptedTotal"
      | "submitScore"
      | "transferOwnership"
      | "updatePaperMetadata"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FinalScorePrepared"
      | "OwnershipTransferred"
      | "PaperRegistered"
      | "PaperUpdated"
      | "ScoreSubmitted"
      | "TotalHandleShared"
  ): EventFragment;

  encodeFunctionData(functionFragment: "MAX_SCORE", values?: undefined): string;
  encodeFunctionData(functionFragment: "MIN_SCORE", values?: undefined): string;
  encodeFunctionData(functionFragment: "getPaper", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getPaperIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlainSum",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listPapers",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "prepareFinalScore",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerPaper",
    values: [BytesLike, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reviewerHasSubmitted",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shareEncryptedTotal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitScore",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePaperMetadata",
    values: [BytesLike, string, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "MAX_SCORE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_SCORE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPaper", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPaperIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlainSum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listPapers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "prepareFinalScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerPaper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reviewerHasSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shareEncryptedTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePaperMetadata",
    data: BytesLike
  ): Result;
}

export namespace FinalScorePreparedEvent {
  export type InputTuple = [paperId: BytesLike, requester: AddressLike];
  export type OutputTuple = [paperId: string, requester: string];
  export interface OutputObject {
    paperId: string;
    requester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaperRegisteredEvent {
  export type InputTuple = [paperId: BytesLike, title: string, track: string];
  export type OutputTuple = [paperId: string, title: string, track: string];
  export interface OutputObject {
    paperId: string;
    title: string;
    track: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaperUpdatedEvent {
  export type InputTuple = [paperId: BytesLike, title: string, track: string];
  export type OutputTuple = [paperId: string, title: string, track: string];
  export interface OutputObject {
    paperId: string;
    title: string;
    track: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreSubmittedEvent {
  export type InputTuple = [
    paperId: BytesLike,
    reviewer: AddressLike,
    reviewCount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    paperId: string,
    reviewer: string,
    reviewCount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    paperId: string;
    reviewer: string;
    reviewCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TotalHandleSharedEvent {
  export type InputTuple = [paperId: BytesLike, requester: AddressLike];
  export type OutputTuple = [paperId: string, requester: string];
  export interface OutputObject {
    paperId: string;
    requester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CipherScribeReview extends BaseContract {
  connect(runner?: ContractRunner | null): CipherScribeReview;
  waitForDeployment(): Promise<this>;

  interface: CipherScribeReviewInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_SCORE: TypedContractMethod<[], [bigint], "view">;

  MIN_SCORE: TypedContractMethod<[], [bigint], "view">;

  getPaper: TypedContractMethod<
    [paperId: BytesLike],
    [CipherScribeReview.PaperStatsStructOutput],
    "view"
  >;

  getPaperIds: TypedContractMethod<[], [string[]], "view">;

  getPlainSum: TypedContractMethod<[paperId: BytesLike], [bigint], "view">;

  listPapers: TypedContractMethod<
    [],
    [CipherScribeReview.PaperStatsStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  prepareFinalScore: TypedContractMethod<
    [paperId: BytesLike],
    [string],
    "nonpayable"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  registerPaper: TypedContractMethod<
    [paperId: BytesLike, title: string, track: string, authorHash: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reviewerHasSubmitted: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  shareEncryptedTotal: TypedContractMethod<
    [paperId: BytesLike],
    [string],
    "nonpayable"
  >;

  submitScore: TypedContractMethod<
    [paperId: BytesLike, encryptedScore: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePaperMetadata: TypedContractMethod<
    [paperId: BytesLike, title: string, track: string, authorHash: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPaper"
  ): TypedContractMethod<
    [paperId: BytesLike],
    [CipherScribeReview.PaperStatsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPaperIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPlainSum"
  ): TypedContractMethod<[paperId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "listPapers"
  ): TypedContractMethod<
    [],
    [CipherScribeReview.PaperStatsStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "prepareFinalScore"
  ): TypedContractMethod<[paperId: BytesLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerPaper"
  ): TypedContractMethod<
    [paperId: BytesLike, title: string, track: string, authorHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reviewerHasSubmitted"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "shareEncryptedTotal"
  ): TypedContractMethod<[paperId: BytesLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "submitScore"
  ): TypedContractMethod<
    [paperId: BytesLike, encryptedScore: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePaperMetadata"
  ): TypedContractMethod<
    [paperId: BytesLike, title: string, track: string, authorHash: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FinalScorePrepared"
  ): TypedContractEvent<
    FinalScorePreparedEvent.InputTuple,
    FinalScorePreparedEvent.OutputTuple,
    FinalScorePreparedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaperRegistered"
  ): TypedContractEvent<
    PaperRegisteredEvent.InputTuple,
    PaperRegisteredEvent.OutputTuple,
    PaperRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "PaperUpdated"
  ): TypedContractEvent<
    PaperUpdatedEvent.InputTuple,
    PaperUpdatedEvent.OutputTuple,
    PaperUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreSubmitted"
  ): TypedContractEvent<
    ScoreSubmittedEvent.InputTuple,
    ScoreSubmittedEvent.OutputTuple,
    ScoreSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "TotalHandleShared"
  ): TypedContractEvent<
    TotalHandleSharedEvent.InputTuple,
    TotalHandleSharedEvent.OutputTuple,
    TotalHandleSharedEvent.OutputObject
  >;

  filters: {
    "FinalScorePrepared(bytes32,address)": TypedContractEvent<
      FinalScorePreparedEvent.InputTuple,
      FinalScorePreparedEvent.OutputTuple,
      FinalScorePreparedEvent.OutputObject
    >;
    FinalScorePrepared: TypedContractEvent<
      FinalScorePreparedEvent.InputTuple,
      FinalScorePreparedEvent.OutputTuple,
      FinalScorePreparedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaperRegistered(bytes32,string,string)": TypedContractEvent<
      PaperRegisteredEvent.InputTuple,
      PaperRegisteredEvent.OutputTuple,
      PaperRegisteredEvent.OutputObject
    >;
    PaperRegistered: TypedContractEvent<
      PaperRegisteredEvent.InputTuple,
      PaperRegisteredEvent.OutputTuple,
      PaperRegisteredEvent.OutputObject
    >;

    "PaperUpdated(bytes32,string,string)": TypedContractEvent<
      PaperUpdatedEvent.InputTuple,
      PaperUpdatedEvent.OutputTuple,
      PaperUpdatedEvent.OutputObject
    >;
    PaperUpdated: TypedContractEvent<
      PaperUpdatedEvent.InputTuple,
      PaperUpdatedEvent.OutputTuple,
      PaperUpdatedEvent.OutputObject
    >;

    "ScoreSubmitted(bytes32,address,uint32,uint64)": TypedContractEvent<
      ScoreSubmittedEvent.InputTuple,
      ScoreSubmittedEvent.OutputTuple,
      ScoreSubmittedEvent.OutputObject
    >;
    ScoreSubmitted: TypedContractEvent<
      ScoreSubmittedEvent.InputTuple,
      ScoreSubmittedEvent.OutputTuple,
      ScoreSubmittedEvent.OutputObject
    >;

    "TotalHandleShared(bytes32,address)": TypedContractEvent<
      TotalHandleSharedEvent.InputTuple,
      TotalHandleSharedEvent.OutputTuple,
      TotalHandleSharedEvent.OutputObject
    >;
    TotalHandleShared: TypedContractEvent<
      TotalHandleSharedEvent.InputTuple,
      TotalHandleSharedEvent.OutputTuple,
      TotalHandleSharedEvent.OutputObject
    >;
  };
}
